### ISSUE TITLE
[Improvement]

### ISSUE THREAD

**Issue by Thelvaen** [bdunderscore/avrc#36]
You can use a WorldConstraint Objects on both avatars, with the parent constraint on "target_reset" removed so avatars will always drop the WCO at the 0.0.0 position on the map, even if they change avatar while on the map, the WCO will be at 0.0.0, so you can put your signals on the WCO and the thing will work even if the avatars did not saw each other, as long as they are on the same map.

**Comment by bdunderscore** [comment]
The problem with having to see each other isn't because of the world constraint, it's because of animator culling. Even if the world constraint is active (and it's only inactive right now to avoid blowing up the bounds avatar perf stat), without the animator running to drive the correct transmitted signals, it won't work.

Now, you could just statically blow up the bounds of the avatar really large to ensure the animator is never culled. I've avoided doing this out of respect for the performance of other players in the instance - I'm only increasing the animator culling range for the two players transmitting and receiving, which requires that the animators be un-culled for long enough to detect each other.

I don't currently see a good solution for this that wouldn't have (potentially severe) performance impacts on other players in the instance, so closing this as a WONTFIX for now.
